title: Demo notes repo
theme: jekyll-theme-merlot
## Keyboard shortcuts
Shortcuts I frequently use: 
- Ctrl-C (copy)
- Ctrl-V (paste)
- Ctrl-Z (undo)

Shortcuts I would like to start using: 
- Ctrl-A (select all)
- Ctrl + X (cut or remove)
- Ctrl + S (Save an open document, file, or webpage)
- Ctrl + N (Open a new window)

## Search Experments
